name: Accelerate NPU UnitTest
run-name: Accelerate NPU UnitTest

on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Accelerate NPU Check]
    types:
      - completed

env:
  HF_HOME: /root/models

jobs:       
  UnitTest:
    runs-on: ascend-910b
    container: 
      image: zhangsibo1129/ubuntu-cann-torch21-py39-accelerate:latest
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
        - /usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
      options: --network host
              --device /dev/davinci_manager
              --device /dev/devmm_svm
              --device /dev/hisi_hdc
              --device /dev/davinci6
              --device /dev/davinci7
    steps:
      - name: Unit-Test
        working-directory: /root/accelerate
        run: | 
          RUN_SLOW=1 pytest -sv tests/deepspeed/
          RUN_SLOW=1 pytest -v  tests/fsdp
          pytest -sv tests/test_accelerator.py
          pytest -sv tests/test_metrics.py
          pytest -sv tests/test_multigpu.py
          pytest -sv tests/test_optimizer.py
          pytest -sv tests/test_state_checkpoint.py
