name: Transformers Docker Image
run-name: Transformers Docker Image

on: push

jobs:
  check_runner:
    runs-on: ascend-910b
    steps:
      - name: Check Runner Status
        run: echo "Done!"

  transformers-docker:
    runs-on: ascend-910b
    needs: check_runner
    steps:
      -
        name: Get Latest Code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SECRET_SSH_KEY }}
          path: llm-tool-ci
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/transformers
          build-args: |
            REF=main
          push: true
          tags: zhangsibo1129/ubuntu-cann-torch21-py39-transformers:latest
