name: Transformers Docker Image
run-name: Transformers Docker Image

on: push

jobs:
  check_runner:
    runs-on: ascend-910b
    steps:
      - name: Check Runner Status
        run: echo "Done!"

  transformers-docker:
    runs-on: ascend-910b
    needs: check_runner
    steps:
      -
        name: Get Latest Code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SECRET_SSH_KEY }}
          path: llm-tool-ci
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build Docker Image
        run: |
          pwd
          cd docker/transformers
          pwd
          docker build -t zhangsibo1129/ubuntu-cann-torch21-py39:latest -f ./Dockerfile .
      -
        name: Push Docker Image
        run: |
          pwd
          cd docker/transformers
          pwd
          docker push zhangsibo1129/ubuntu-cann-torch21-py39:latest
