name: Build Docker Images
run-name: Build Docker Images

on:
  schedule:
     - cron: '0 0 * * *'

jobs:
  check-runner:
    runs-on: ascend-910b
    steps:
      - name: Check Runner Status
        run: echo "Done!"

  transformers-docker:
    runs-on: ascend-910b
    needs: check-runner
    steps:
      -
        name: Get Latest Code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SECRET_SSH_KEY }}
          path: llm-tool-ci
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build Docker Image
        run: |
          cd llm-tool-ci/docker/transformers
          docker build --no-cache -t zhangsibo1129/ubuntu-cann-torch21-py39-transformers:latest -f ./Dockerfile .
      -
        name: Push Docker Image
        run: |
          docker push zhangsibo1129/ubuntu-cann-torch21-py39-transformers:latest

  fschat-docker:
    runs-on: ascend-910b
    needs: check-runner
    steps:
      -
        name: Get Latest Code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SECRET_SSH_KEY }}
          path: llm-tool-ci
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build Docker Image
        run: |
          cd llm-tool-ci/docker/fschat
          docker build --no-cache -t zhangsibo1129/ubuntu-cann-torch21-py39-fschat:latest -f ./Dockerfile .
      -
        name: Push Docker Image
        run: |
          docker push zhangsibo1129/ubuntu-cann-torch21-py39-fschat:latest

  peft-docker:
    runs-on: ascend-910b
    needs: check-runner
    steps:
      - 
        name: Get Latest Code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SECRET_SSH_KEY }}
          path: llm-tool-ci
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Build Docker Image
        run: |
          cd llm-tool-ci/docker/peft
          docker build --no-cache -t zhangsibo1129/ubuntu-cann-torch21-py39-peft:latest -f ./Dockerfile .
      - 
        name: Push Docker Image
        run: |
          docker push zhangsibo1129/ubuntu-cann-torch21-py39-peft:latest