name: PEFT Scan Models
run-name: PEFT Scan Models

on:
  workflow_run:
    workflows: [PEFT Official Tests]
    types:
      - completed


jobs:
  scan_models:
    runs-on: ascend-910b
    container:
      image: zhangsibo1129/ubuntu-cann-torch21-py39:latest
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
        - /usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
        - /data/disk3/action/models/hub/:/opt/big_models/
        - /data/disk3/action/nlp_data/:/opt/nlp_data/
        - /data/disk3/action/envs/peft/torch_npu:/root/miniconda/envs/torch_npu
        - /data/disk3/action/repo:/__w/llm-tool-ci/llm-tool-ci
        - /data/disk3/action/projects/peft:/__w/llm-tool-ci/llm-tool-ci/peft
      options: --network host
        --device /dev/davinci_manager
        --device /dev/devmm_svm
        --device /dev/hisi_hdc
        --device /dev/davinci6
        --device /dev/davinci7
    steps:
      - name: Preprocess
        working-directory: /__w/llm-tool-ci/llm-tool-ci/llm-tool-ci
        run: |
          cp peft_test/scan_models/sequence_classification_lora.py /__w/llm-tool-ci/llm-tool-ci/peft/
          cp peft_test/peft-model-test-map.json /__w/llm-tool-ci/llm-tool-ci/peft/
      - name: Run Scan Models
        timeout-minutes: 20
        working-directory: /__w/llm-tool-ci/llm-tool-ci/peft
        run: |
          python sequence_classification_lora.py peft-model-test-map.json
          echo 'scan models done.'
          cp peft-models.json /__w/llm-tool-ci/llm-tool-ci/llm-tool-ci/
          echo 'peft-models.json copy done.'
  update_readme:
    runs-on: ascend-910b
    needs: scan_models
    container:
      image: zhangsibo1129/ubuntu-cann-torch21-py39:latest
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
        - /usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
        - /data/disk3/action/envs/peft/torch_npu:/root/miniconda/envs/torch_npu
        - /data/disk3/action/repo:/__w/llm-tool-ci/llm-tool-ci
      options: --network host
        --device /dev/davinci_manager

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SECRET_SSH_KEY }}
          path: llm-tool-ci
          clean: false
      - name: Write Table to README
        working-directory: /__w/llm-tool-ci/llm-tool-ci/llm-tool-ci
        run: |
          python update_table.py -f README.md -t peft-models.json -n peft

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update peft Table
          repository: /__w/llm-tool-ci/llm-tool-ci/llm-tool-ci
          file_pattern: 'README.md'
