name: PEFT NPU Build
run-name: PEFT NPU Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

jobs:
  check_runner:
    runs-on: ascend-910b
    steps:
      - name: Check Runner Status
        run: echo "Check runner done!"

  check_npu_environment:
    runs-on: ascend-910b
    needs: check_runner
    strategy:
      matrix:
        machine_type: [single-npu, multi-npu]
    container:
      image: zhangsibo1129/ubuntu-cann-torch21-py39:latest
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
        - /usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
      options: --network host
               --device /dev/davinci_manager
               --device /dev/devmm_svm
               --device /dev/hisi_hdc
               --device /dev/davinci6
               ${{ matrix.machine_type == 'multi-npu' && '--device /dev/davinci7' || ''}}
    steps:
      - name: NPU-SMI
        run: npu-smi info
      - name: Show torch information
        run: |
          python << EOF 
          if __name__ == '__main__':
              import torch
              import torch_npu
              print(f"Device Name: {torch.npu.get_device_name(0)}")
              print(f"Device Count: {torch.npu.device_count()}")
              print(f"Device Available: {torch.npu.is_available()}")
          EOF

  install_peft:
    runs-on: ascend-910b
    needs: check_npu_environment
    container:
      image: zhangsibo1129/ubuntu-cann-torch21-py39:latest
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
        - /usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
        - /data/disk3/action/envs/peft:/root/data
        - /data/disk3/action/repo:/__w/llm-tool-ci/llm-tool-ci
        - /data/disk3/action/projects/peft:/__w/llm-tool-ci/llm-tool-ci/peft

      options: --network host
               --device /dev/davinci_manager
               --device /dev/devmm_svm
               --device /dev/hisi_hdc
               --device /dev/davinci6
    steps:
        - name: Get peft Latest Code
          uses: actions/checkout@v4
          with:
            repository: huggingface/peft
            ssh-key: ${{ secrets.SECRET_SSH_KEY }}
            path: peft
            clean: true
        - name: Pull peft
          working-directory: /__w/llm-tool-ci/llm-tool-ci/peft
          run: |
            git pull
            pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
            pip install peft transformers accelerate pytest pytest-cov pytest-xdist parameterized datasets -i https://pypi.mirrors.ustc.edu.cn/simple
        - name: Get CI Code
          uses: actions/checkout@v4
          with:
            ssh-key: ${{ secrets.SECRET_SSH_KEY }}
            path: llm-tool-ci
        - name: Import Verification
          working-directory: /__w/llm-tool-ci/llm-tool-ci/peft
          run: |
            python << EOF
            if __name__ == '__main__':
                from peft import (
                  AutoPeftModel,
                  AutoPeftModelForCausalLM,
                  AutoPeftModelForFeatureExtraction,
                  AutoPeftModelForQuestionAnswering,
                  AutoPeftModelForSeq2SeqLM,
                  AutoPeftModelForSequenceClassification,
                  AutoPeftModelForTokenClassification,
                  PeftModel,
                  PeftModelForCausalLM,
                  PeftModelForFeatureExtraction,
                  PeftModelForQuestionAnswering,
                  PeftModelForSeq2SeqLM,
                  PeftModelForSequenceClassification,
                  PeftModelForTokenClassification,
              )
            EOF
        - name: Persistent Python Interpreter
          run: |
            rm -rf /root/data/torch_npu
            mv /root/miniconda/envs/torch_npu /root/data
