name: Transformers Check Environment
run-name: Transformers Check Environment

on:
  push:
    branches:
      - main

jobs:
  check_runner:
    runs-on: ascend-910b
    steps:
      - 
        name: Check Runner Status
        run: echo "Done!"

  check_environment:
    runs-on: ascend-910b
    needs: check_runner
    strategy:
      matrix:
        machine_type: [single-npu, multi-npu]
    container: 
      image: zhangsibo1129/ubuntu-cann-torch21-py39-transformers:latest
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
        - /usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
      options: --network host
               --device /dev/davinci_manager
               --device /dev/devmm_svm
               --device /dev/hisi_hdc
               --device /dev/davinci6
               ${{ matrix.machine_type == 'multi-npu' && '--device /dev/davinci7' || ''}}
    steps:
      - 
        name: NPU-SMI
        run: npu-smi info
      - 
        name: Show torch information
        run: |
          python << EOF 
          if __name__ == '__main__':
              import torch
              import torch_npu
              print(f"Device Name: {torch.npu.get_device_name(0)}")
              print(f"Device Count: {torch.npu.device_count()}")
              print(f"Device Available: {torch.npu.is_available()}")
          EOF
      - 
        name: Import Verification
        run: |
            python << EOF
            if __name__ == '__main__':
                import transformers
                from transformers import is_torch_npu_available
                if not is_torch_npu_available():
                    raise ImportError('NPU is not available')
                from transformers import pipeline
                from transformers import AutoConfig
                from transformers import AutoTokenizer
                from transformers import AutoModel
                from transformers import Trainer
            EOF
